version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postressql/postgres_data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=diamant_studio_db
      - POSTGRES_USER=diamant_studio_admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
  web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/app  
      ports:
        - "8000:8000"
      env_file:
        - .env
      depends_on:
        - db
        # diamantstudiogrodno.pagekite.me	
  bot:
      build: .
      command: python run_bot.py
      volumes:
        - .:/app
      
      environment:         
        - TELEGRAM_BOT_TOKEN=8560836641:AAEKsBAUFHWWmz3H3GFmEL4PIuIQSKYPRoo
        - TELEGRAM_ADMIN_CHAT_ID=698071646
        - DB_NAME=diamant_studio_db
        - DB_USER=diamant_studio_admin
        - DB_PASSWORD=admin
        - DB_HOST=db
        - DB_PORT=5432
      depends_on:
        - db
        - web

  tunnel:
    image: node:20-alpine
    restart: always
    command: sh -c "npm install -g localtunnel && lt --port 8000 --local-host web --host https://localtunnel.me"
     
    depends_on:
      - web

volumes:
  postgres_data:




    