# Generated by Django 6.0.6 on 2026-07-06 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('completed', 'Завершена'), ('canceled', 'Отменена')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='masters.master')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='services.service')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
    ]
