# Generated by Django 6.0.8 on 2026-09-30 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0004_alter_application_options_and_more'),
        ('masters', '0011_alter_master_options_alter_master_experience_and_more'),
        ('services', '0002_auto_20260913_1509'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['appointment_date', 'appointment_time'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AddField(
            model_name='application',
            name='client_telegram_chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('master', 'appointment_date', 'appointment_time'), name='unique_master_appointment'),
        ),
    ]
