# Generated by Django 6.0.6 on 2026-07-22 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_master_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPortFolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='masters/portfolio/', verbose_name='Фото работы')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='masters.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Фотография работы',
                'verbose_name_plural': 'Галерея работ',
            },
        ),
    ]
