# Generated by Django 6.0.8 on 2026-08-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_reviews'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={},
        ),
        migrations.AddIndex(
            model_name='master',
            index=models.Index(fields=['is_active'], name='masters_mas_is_acti_283da4_idx'),
        ),
    ]
