# Generated by Django 6.0.8 on 2026-08-18 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0003_application_client_name_application_client_phone_and_more'),
        ('masters', '0007_reviews'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='application',
            name='unique_master_appointment',
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['appointment_date'], name='appoinments_appoint_c597cc_idx'),
        ),
    ]
