# Generated by Django 6.0.8 on 2026-09-13 12:09
from django.db import migrations
from decimal import Decimal

def populate_services(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    
    services_data = [
        {"name": "Макияж", "price": Decimal("60.00"), "duration": 60},
        {"name": "Брови", "price": Decimal("25.00"), "duration": 40},
        {"name": "Ламинирование ресниц", "price": Decimal("45.00"), "duration": 50},
        {"name": "Мужские стрижки", "price": Decimal("35.00"), "duration": 45},
        {"name": "Оформление бороды", "price": Decimal("25.00"), "duration": 30},
        {"name": "Стрижка машинкой", "price": Decimal("20.00"), "duration": 20},
        {"name": "Чистка лица", "price": Decimal("55.00"), "duration": 90},
        {"name": "Уходовые процедуры", "price": Decimal("40.00"), "duration": 45},
        {"name": "Пилинг", "price": Decimal("50.00"), "duration": 40},
        {"name": "Массаж лица", "price": Decimal("30.00"), "duration": 30},
    ]
    
    for item in services_data:
        Service.objects.get_or_create(
            name=item["name"],
            defaults={"price": item["price"], "duration": item["duration"]}
        )

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(populate_services),
    ]
    