# Generated by Django 6.0.6 on 2026-07-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='work_end',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AddField(
            model_name='master',
            name='work_start',
            field=models.TimeField(default='08:00'),
        ),
    ]
