# Generated by Django 6.0.6 on 2026-07-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_master_work_end_master_work_start'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='master', to='services.service', verbose_name='Услуги'),
        ),
    ]
