# Generated by Django 6.0.6 on 2026-07-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_master_services'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='masters', to='services.service', verbose_name='Услуги'),
        ),
    ]
