# Generated by Django 6.0.6 on 2026-07-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_master_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='experience',
            field=models.PositiveIntegerField(default=1, verbose_name='Опыт работы  (лет)'),
        ),
    ]
