# Generated by Django 6.0.8 on 2026-09-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_alter_master_options_and_more'),
        ('masters', '0009_auto_20260913_1516'),
    ]

    operations = [
    ]
