# Generated by Django 6.0.8 on 2026-09-30 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_merge_20260913_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['name'], 'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterField(
            model_name='master',
            name='experience',
            field=models.PositiveIntegerField(default=1, verbose_name='Опыт работы (лет)'),
        ),
        migrations.CreateModel(
            name='MasterDayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата выходного/отпуска')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='Причина (выходной, отпуск, больничный)')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='masters.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Выходной/Отпуск мастера',
                'verbose_name_plural': 'Выходные и отпуска мастеров',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('master', 'date'), name='unique_master_day_off')],
            },
        ),
    ]
